name: Deploy Music Bot

on:
  push:
    branches:
      - main
      - 49-add-auto-deployment

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Install SSH agent
    - name: Install SSH Agent
      uses: webfactory/ssh-agent@0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Deploy to the server
    - name: Deploy and Restart Music Bot
      run: |
        ssh -o StrictHostKeyChecking=no music-bot-hosting@213.199.57.67 << 'EOF'
        pm2 delete music-bot || true
        cd music-bot
        git pull origin main
        pm2 start main.py --name music-bot
        EOF
